/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import modelo.Usuarios;
import modelo.Pistas;
import java.sql.Time;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author isard
 */
public class DiaSeleccionadoAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DiaSeleccionadoAdmin
     */
    public DiaSeleccionadoAdmin() {
        initComponents();
    }
    
    public JLabel getTxtPISTA() {
        return txtPISTA;
    }

    public void setTxtPISTA(String txtPISTA){
        this.txtPISTA.setText("PISTA: "+txtPISTA);
    }

    public void setjLabel1(String jLabel1) {
        this.jLabel1.setText("Dia: "+jLabel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReservar10 = new javax.swing.JButton();
        btnReservar11 = new javax.swing.JButton();
        txtPISTA = new javax.swing.JLabel();
        btnReservar12 = new javax.swing.JButton();
        btnReservar20 = new javax.swing.JButton();
        btnReservar13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReservar17 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtHora17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHora13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHora12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReservar19 = new javax.swing.JButton();
        btnReservar18 = new javax.swing.JButton();
        txtHora20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHora19 = new javax.swing.JLabel();
        txtHora18 = new javax.swing.JLabel();
        txtHora10 = new javax.swing.JLabel();
        txtHora11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReservar10.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar10.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar10.setText("Reservar");
        btnReservar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar10ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        btnReservar11.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar11.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar11.setText("Reservar");
        btnReservar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        txtPISTA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPISTA.setForeground(new java.awt.Color(0, 0, 0));
        txtPISTA.setText("PISTA: ");
        getContentPane().add(txtPISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        btnReservar12.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar12.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar12.setText("Reservar");
        btnReservar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        btnReservar20.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar20.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar20.setText("Reservar");
        btnReservar20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar20ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        btnReservar13.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar13.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar13.setText("Reservar");
        btnReservar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar13ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btnReservar17.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar17.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar17.setText("Reservar");
        btnReservar17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar17ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("17:00 - 18:00 ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        txtHora17.setForeground(new java.awt.Color(0, 0, 0));
        txtHora17.setText("Pista deshabilitada");
        getContentPane().add(txtHora17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("12:00 - 13:00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txtHora13.setForeground(new java.awt.Color(0, 0, 0));
        txtHora13.setText("Pista deshabilitada");
        getContentPane().add(txtHora13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("11:00 - 12:00");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        txtHora12.setForeground(new java.awt.Color(0, 0, 0));
        txtHora12.setText("Pista deshabilitada");
        getContentPane().add(txtHora12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("19:00 - 20:00");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("10:00 - 11:00");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btnReservar19.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar19.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar19.setText("Reservar");
        btnReservar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar19ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        btnReservar18.setBackground(new java.awt.Color(0, 0, 0));
        btnReservar18.setForeground(new java.awt.Color(255, 255, 255));
        btnReservar18.setText("Reservar");
        btnReservar18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar18ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        txtHora20.setForeground(new java.awt.Color(0, 0, 0));
        txtHora20.setText("Pista deshabilitada");
        getContentPane().add(txtHora20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("20:00 - 21:00");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("13:00 - 14:00");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        txtHora19.setForeground(new java.awt.Color(0, 0, 0));
        txtHora19.setText("Pista deshabilitada");
        getContentPane().add(txtHora19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        txtHora18.setForeground(new java.awt.Color(0, 0, 0));
        txtHora18.setText("Pista deshabilitada");
        getContentPane().add(txtHora18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        txtHora10.setForeground(new java.awt.Color(0, 0, 0));
        txtHora10.setText("Pista deshabilitada");
        getContentPane().add(txtHora10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        txtHora11.setForeground(new java.awt.Color(0, 0, 0));
        txtHora11.setText("Pista deshabilitada");
        getContentPane().add(txtHora11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("18:00 - 19:00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(224, 204, 188));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 350, 270));

        Panel.setBackground(new java.awt.Color(144, 132, 108));
        Panel.setForeground(new java.awt.Color(0, 0, 0));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("PericosPadel S.L");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 583, 361));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        Panel.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        btnInicio.setBackground(new java.awt.Color(0, 0, 0));
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        Panel.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar10ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("10:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar10.setVisible(false);
    }//GEN-LAST:event_btnReservar10ActionPerformed

    private void btnReservar17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar17ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("17:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar17.setVisible(false);
    }//GEN-LAST:event_btnReservar17ActionPerformed

    private void btnReservar12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar12ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("12:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar12.setVisible(false);
    }//GEN-LAST:event_btnReservar12ActionPerformed

    private void btnReservar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar11ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("11:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar11.setVisible(false);
    }//GEN-LAST:event_btnReservar11ActionPerformed

    private void btnReservar18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar18ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("18:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar18.setVisible(false);
    }//GEN-LAST:event_btnReservar18ActionPerformed

    private void btnReservar20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar20ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("20:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar20.setVisible(false);
    }//GEN-LAST:event_btnReservar20ActionPerformed

    private void btnReservar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar19ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("19:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar19.setVisible(false);
    }//GEN-LAST:event_btnReservar19ActionPerformed

    private void btnReservar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar13ActionPerformed
        // TODO add your handling code here:
        Time horaseleccionada = java.sql.Time.valueOf("13:00:00");
        try {
            Controlador.ReservarPistaAdmin(horaseleccionada);
        } catch (SQLException ex) {
            Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnReservar13.setVisible(false);
    }//GEN-LAST:event_btnReservar13ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Controlador.VolverDiaSeleccionadoAdmin();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        Controlador.InicioDiaSeleccionadoAdmin();
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaSeleccionadoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaSeleccionadoAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnInicio;
    public javax.swing.JButton btnReservar10;
    public javax.swing.JButton btnReservar11;
    public javax.swing.JButton btnReservar12;
    public javax.swing.JButton btnReservar13;
    public javax.swing.JButton btnReservar17;
    public javax.swing.JButton btnReservar18;
    public javax.swing.JButton btnReservar19;
    public javax.swing.JButton btnReservar20;
    private javax.swing.JButton btnVolver;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel txtHora10;
    public javax.swing.JLabel txtHora11;
    public javax.swing.JLabel txtHora12;
    public javax.swing.JLabel txtHora13;
    public javax.swing.JLabel txtHora17;
    public javax.swing.JLabel txtHora18;
    public javax.swing.JLabel txtHora19;
    public javax.swing.JLabel txtHora20;
    public javax.swing.JLabel txtPISTA;
    // End of variables declaration//GEN-END:variables
}
